config/routes.rb
Rails.application.routes.draw do
  root 'pokes#index'

  get 'static_pages/contact'
  get 'static_pages/about'

  resources :pokes
end

app/models/ability.rb
class Ability < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_poke.rb
class DataPoke < ApplicationRecord
  belongs_to :poke
  has_many :data_poke_abilities
  has_many :abilities, through: :data_poke_abilities
  has_many :data_poke_items
  has_many :items, through: :datapokeitems
  has_many :data_poke_teammates
  has_many :teammates, through: :data_poke_teammates, source: :poke
  has_one :data_viability
end

app/models/data_poke_ability.rb
class DataPokeAbility < ApplicationRecord
  belongs_to :ability
  belongs_to :data_poke
end

app/models/data_poke_item.rb
class DataPokeItem < ApplicationRecord
  belongs_to :item
  belongs_to :data_poke
end

app/models/data_poke_move.rb
class DataPokeMove < ApplicationRecord
  belongs_to :move
  belongs_to :data_poke
end

app/models/data_poke_teammate.rb
class DataPokeTeammate < ApplicationRecord
  belongs_to :poke
  belongs_to :data_poke
end

app/models/data_smogon.rb
class DataSmogon < ApplicationRecord
end

app/models/data_viability.rb
class DataViability < ApplicationRecord
  belongs_to :data_poke
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/move.rb
class Move < ApplicationRecord
end

app/models/nature.rb
class Nature < ApplicationRecord
end

app/models/poke.rb
class Poke < ApplicationRecord
  validates :name,      presence: true, uniqueness: true
end

app/models/stat.rb
class Stat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pokes_controller.rb
class PokesController < ApplicationController
  before_action :set_poke, only: [:show, :edit, :update, :destroy]

  # GET /pokes
  # GET /pokes.json
  def index
    @pokes = Poke.all.order(:order)
  end

  # GET /pokes/1
  # GET /pokes/1.json
  def show
  end

  # GET /pokes/new
  def new
    @poke = Poke.new
  end

  # GET /pokes/1/edit
  def edit
  end

  # POST /pokes
  # POST /pokes.json
  def create
    @poke = Poke.new(poke_params)

    respond_to do |format|
      if @poke.save
        format.html { redirect_to @poke, notice: 'Poke was successfully created.' }
        format.json { render :show, status: :created, location: @poke }
      else
        format.html { render :new }
        format.json { render json: @poke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokes/1
  # PATCH/PUT /pokes/1.json
  def update
    respond_to do |format|
      if @poke.update(poke_params)
        format.html { redirect_to @poke, notice: 'Poke was successfully updated.' }
        format.json { render :show, status: :ok, location: @poke }
      else
        format.html { render :edit }
        format.json { render json: @poke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokes/1
  # DELETE /pokes/1.json
  def destroy
    @poke.destroy
    respond_to do |format|
      format.html { redirect_to pokes_url, notice: 'Poke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poke
      @poke = Poke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poke_params
      params.require(:poke).permit(:name, :weight, :order)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title = '')
    base_title = 'Pokemon Usage Statistics'
    if title.empty?
      return base_title
    else
      return title + ' | ' + base_title
    end
  end
end

app/helpers/pokes_helper.rb
module PokesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}
    %title= page_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{class: "#{controller_name} #{action_name}"}
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{'aria-controls': 'navbar', 'aria-expanded': 'false', 'data-target': '#navbar', 'data-toggle': 'collapse', type: 'button'}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to 'Pokes Page', pokes_path
        #navbar.navbar-collapse.collapse
          %ul.nav.navbar-nav
            %li= link_to 'Home', pokes_path
            %li= link_to 'placeholder', '#'
            %li.dropdown
              %a.dropdown-toggle{'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-toggle': 'dropdown', href: '#', role: 'button'}
                dropdown placeholder
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'placeholder2', '#'
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'About', static_pages_about_path
            %li= link_to 'Contact', static_pages_contact_path
    .container
      = yield

app/views/pokes/_form.html.haml
= form_for(poke) do |f|
  - if poke.errors.any?
    #error_explanation
      %h2
        = pluralize(poke.errors.count, "error")
        prohibited this poke from being saved:
      %ul
        - poke.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :weight
    = f.number_field :weight
  .field
    = f.label :order
    = f.number_field :order
  .actions
    = f.submit

app/views/pokes/edit.html.haml
%h1 Editing Poke
= render 'form', poke: @poke
= link_to 'Show', @poke
|
= link_to 'Back', pokes_path

app/views/pokes/index.html.haml
-provide(:title, 'Pokemon Index')
%p#notice= notice
%h1= yield(:title)
%table.table.table-condensed.datatable
  %thead
    %tr
      %th Name
      %th Weight
      %th Order
      %th
      %th
      %th
  %tbody
    - @pokes.each do |poke|
      %tr
        %td= poke.name
        %td= poke.weight
        %td= poke.order
        %td= link_to 'Show', poke
        %td= link_to 'Edit', edit_poke_path(poke)
        %td= link_to 'Destroy', poke, method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'New Poke', new_poke_path

app/views/pokes/new.html.haml
%h1 New Poke
= render 'form', poke: @poke
= link_to 'Back', pokes_path

app/views/pokes/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @poke.name
%p
  %strong Weight:
  = @poke.weight
%p
  %strong Order:
  = @poke.order
= link_to 'Edit', edit_poke_path(@poke)
|
= link_to 'Back', pokes_path

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/about.html.haml
-provide(:title, 'About')
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.haml
-provide(:title, 'Contact')
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>